[Refactor] 레포지토리 초기 세팅
saramdle/blog-team-three-CoderHive-BE pull request #23
Opened 2023-03-23 15:04 UTC by hxnsxxm

## Summary
모든 repository 초기 세팅

## Describe your changes

## Issue number and link
#20

2023-03-23 15:15 UTC, Gonggibab approved these changes
👍🏻

2023-03-24 01:40 UTC, GGHDMS requested changes
한샘님 레포지토리에 user 가 meber 로 변경 되어 있는지 확인해 주세요

2023-03-24 01:57 UTC, hxnsxxm commented
MemberRepository, MemberApplyRepository와는 별개로 UserRepository랑 UserApplyRepository가 살아있네요. 제 로컬에는 없긴 한데 user가

2023-03-24 02:28 UTC, GGHDMS approved these changes
👍

2023-03-24 04:58 UTC, merged