[Refactor] 회원 등록 기능 수정 및 사용자 유효성(유저, 게스트) 검사 요청 기능 구현
saramdle/blog-team-three-CoderHive-BE pull request #54
Opened 2023-05-12 06:47 UTC by hxnsxxm

## Summary
회원 등록 기능 수정 및 사용자 유효성(유저, 게스트) 검사 요청 기능 구현

## Describe your changes
- [X] 회원 가입 및 사용자 유효성(USER or QUEST) 판단을 위한 기능을 위한 DTO를 추가하였습니다.
`SignUpDto`, `SignUpResponse`
  - Validation 로직 추가
- [X] 회원 가입 로직 변경하였습니다.
  - 회원 가입에 Service 메소드를 호출하는 과정에서 `SignUpRequest`와 `MemberPrinciple`을 `SignUpDto`로 감싸서 전달하도록 수정하였습니다.
  - `SignUpDto` + `Job` -> `Member` 엔티티로 변환하는 메소드 추가하였습니다.
  - `DB` 저장 이후 `Member` 엔티티를 `SignUpResponse`로 변환하여 반환하도록 하였습니다.
- [X] 사용자 유효성 검사 요청 기능을 구현하였습니다.
  - `email`을 받아서 해당 사용자의 `ROLE`을 검사한 이후에 `SignUpResponse`를 반환하도록 하였습니다.
- [X] 테스트 코드 추가
  - `SignUpRequestTest` 필드값 검증 테스트
  - `MemberServiceTest` 회원가입 기능 테스트

## Issue number and link
#51 

## TODO
- 사용자 유효성 검사 요청 기능에 검증 로직 추가
  - 소셜 로그인 여부 확인 로직 추가
  - 유효성 검증 대상(email)과 로그인 유저(MemberPrincipal)이 동일한 지 검증 로직 추가

2023-05-12 07:58 UTC, an2z commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        Job job = jobRepository.findById(signUpDto.jobId()).orElseThrow();
마찬가지로 `JobService`에 `findOne()` 기능을 사용하면 `orElseThrow()`를 없앨수 있을거 같아요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/response/SignUpResponse.java
> +                .isSignUp(member.getMemberRole() == USER ? true : false)
삼항연산자가 필요 없을거 같아요!
member.getMemberRole() == USER 연산 자체의 반환값이 `true`, `false`이지 않을까요?!

2023-05-12 07:58 UTC, jolly-n commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
저는 build 관련 수정은 Chore 커밋 타입을 사용중인데 의견 나눈 뒤에 통일하는게 좋을것 같네요!

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        if (!member.getMemberRole().equals(MemberRole.GUEST)) {
저는 `Member`의 상태를 확인하는 것은 `Member` 클래스의 책임이라고 생각해요!
무분별한 `getter` 사용을 줄일 수 있을거 같은데 어떻게 생각하시나요?

2023-05-12 07:58 UTC, jolly-n commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/service/MemberServiceTest.java
> +        Member savedMember = oMember.get();
oMember 변수를 딱히 재사용하고 있지 않으니까 findByEmail().get()으로 한줄로 표현해도 되지 않을까 하는 생각이 드는데 따로 oMember를 변수로 저장해주신 이유가 있을까요?
```
Member savedMember = memberRepository.findByEmail(questMembers.getEmail()).get();
```

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/SignUpDto.java
> +                .jobId(Long.parseLong(signUpRequest.jobId()))
`jobId`를 signUpReqeust에서는 String 타입으로 받은 뒤 여기서 parseLong()으로 타입 변환을 해주는 이유가 무엇인가요?
signUpReqeust 자체에서 Long 타입으로 받지 않는 이유가 궁금합니다!

2023-05-12 07:58 UTC, jolly-n commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequestTest.java
> +}
파일 마지막에 빈 줄을 추가해주세요!

2023-05-12 07:58 UTC, jolly-n commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequestTest.java
> +        }
그냥 콘솔 출력으로 테스트를 진행하는 것은 좋지 않을거 같아요..!
정확한 검증이 이뤄질 수 있는 테스트 코드를 작성해주시는게 좋을거 같아요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequest.java
>          @NotBlank(message = "닉네임은 필수 입력값입니다.")
가독성을 위해 필드간 개행을 추가해주는 것이 좋을거 같아요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
> +//                .toUri();
주석은 정리해줘도 될 것 같아요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
>      }
해당 검증 api는 언제 사용될까요?

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/entity/Member.java
> +    }
저는 개인적으로 엔티티에 DTO가 들어오는 것은 좋지 않을 거 같다고 생각하는데 어떻게 생각하시나요?

제 생각으로는 이렇게 엔티티가 DTO를 참조하고 있는 형태라면 ,
클라이언트쪽에 변경이 생겨 `SignUpDTO`에 변경이 생겼을때 가장 중요한 도메인까지 영향을 받게 되기 때문에 좋지 않다고 생각하고 있어요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new EntityNotFoundException(String.format(NOT_FOUND_MEMBER, signUpDto.email())));
searchMember()와 동일한 코드인것 같네요!
이미 구현되어 있는 기능을 최대한 활용해야 중복 코드를 줄일 수 있을 것 같아요.

2023-05-12 07:58 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        return SignUpResponse.from(memberRepository.findByEmail(email).orElseThrow());
마찬가지로 구현되어 있는 searchMember()를 사용해주세요!

2023-05-12 08:03 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/response/SignUpResponse.java
> +                .isSignUp(member.getMemberRole() == USER ? true : false)
👍

2023-05-12 08:07 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        Job job = jobRepository.findById(signUpDto.jobId()).orElseThrow();
`findOne()`이 사라졌다고 하네요. `orElseThrow()`는 `Optional<>`때문이었는데 그냥 `get()`으로 바꾸겠습니다.
https://okky.kr/questions/642196

2023-05-12 08:09 UTC, hxnsxxm commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/service/MemberServiceTest.java
> +        Member savedMember = oMember.get();
아뇨 없습니다. 이건 한 줄로 할게요

2023-05-12 08:10 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
> +//                .toUri();
👍

2023-05-12 08:13 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new EntityNotFoundException(String.format(NOT_FOUND_MEMBER, signUpDto.email())));
👍

2023-05-12 08:14 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        return SignUpResponse.from(memberRepository.findByEmail(email).orElseThrow());
👍

2023-05-12 08:21 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        return SignUpResponse.from(memberRepository.save(member));
member.update()를 통해 JPA가 Dirty Checking하여 DB에 업데이트를 쿼리를 날리기 때문에 save()를 해줄 필요가 없어요.

update 메소드의 반환값으로 Member를 받는 방식으로 변경하면 어떨까요?
```
Member updatedMember = member.update(signUpDto, job);
return SignResponse.from(updatedMember);
```

2023-05-12 08:59 UTC, koseha commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
👍

2023-05-12 09:11 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        if (!member.getMemberRole().equals(MemberRole.GUEST)) {
👍

2023-05-12 09:13 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        Job job = jobRepository.findById(signUpDto.jobId()).orElseThrow();
제가 구현해두었어요!! 확인해주세요!!

2023-05-12 09:17 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/entity/Member.java
> +    }
👍

2023-05-12 09:26 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        return SignUpResponse.from(memberRepository.save(member));
👍

2023-05-12 10:18 UTC, Gonggibab approved these changes
고생하셨습니다

2023-05-12 17:11 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        if (!member.isGuest()) {
제가 예시를 `isGuest()`로 했었지만, !부정을 사용하는 것보다 `isNotGuest()`이거나 `isUser()`로 반환이 true일때 그대로 true를 사용하도록 하는 것이 가독성에 좋다고 하더라구요!

물론 지금은 복잡하지 않기 때문에 !부정을 건다고 해서 크게 가독성을 해치지 않아서 문제될 것은 없지만, 
함께 가독성 좋은 코드가 무엇일지 고민해볼 수 있었으면 좋겠어요.😄

2023-05-12 17:11 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
>  //        Long memberId = memberService.signUp(SignUpDto.of(signUpRequest, memberPrincipal.getEmail()));
해당 주석도 필요없는 내용이라면 지워도 되지 않을까요?

2023-05-12 17:11 UTC, an2z commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
>          //return ResponseEntity.created(location).body("회원 가입 성공");
해당 주석도 필요없는 내용이라면 지워도 되지 않을까요?

2023-05-13 06:12 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        if (!member.isGuest()) {
저도 고민했던 부분인데 확실히 그렇겠네요 👍

2023-05-13 06:22 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
>  //        Long memberId = memberService.signUp(SignUpDto.of(signUpRequest, memberPrincipal.getEmail()));
👍

2023-05-13 06:22 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/controller/MemberController.java
>          //return ResponseEntity.created(location).body("회원 가입 성공");
👍

2023-05-13 07:50 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        Job job = jobRepository.findById(signUpDto.jobId()).orElseThrow();
Service 간 참조는 크게 고려할 사항이 아닌가요??

2023-05-13 08:09 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +        Job job = jobRepository.findById(signUpDto.jobId()).orElseThrow();
이부분에 대해서는 Controller에서 JobService를 호출하고 다시 MemberService를 호출하는 방식으로 바꿔보겠습니다.

2023-05-16 07:47 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/SignUpDto.java
> +                .jobId(Long.parseLong(signUpRequest.jobId()))
validation이 Long타입이 안돼서 String으로 먼저 받고 Long으로 변환하는 식으로 사용한다고 하더라구요.
Int로는 되지만 이미 Long을 사용해서 위와 같이 사용했습니다

2023-05-16 08:59 UTC, hxnsxxm commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequestTest.java
> +        }
👍

2023-05-16 08:59 UTC, hxnsxxm commented on src/test/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequestTest.java
> +}
👍

2023-05-16 09:00 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequest.java
>          @NotBlank(message = "닉네임은 필수 입력값입니다.")
👍

2023-05-17 02:27 UTC, jolly-n requested changes

2023-05-17 02:27 UTC, an2z commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/response/SignUpResponse.java
> +                .isSignUp(member.getMemberRole() == USER)
나중에 이부분도 getter로 꺼내와서 확인하는게 아니라 Member 객체가 스스로 자신이 USER인지 확인하는 쪽으로 개선하면 좋을거 같아요!

2023-05-17 02:27 UTC, an2z commented on src/main/java/net/blogteamthreecoderhivebe/global/validation/ValidationSequence.java
> +@GroupSequence({Default.class, NotEmptyGroup.class, PatternCheckGroup.class,})
마지막 PatternCheckGroup.class 뒤에 ,가 있는데 괜찮은가요?

2023-05-17 02:27 UTC, an2z commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/service/MemberService.java
> +            new EntityNotFoundException(String.format(NOT_MATCH_MEMBER_GUEST, signUpDto.email()));
회원이 게스트가 아닐때 아무 일도 일어나지 않을거 같아요..!
의도대로 실제로 회원이 게스트가 아닐때 예외가 발생하는지 테스트 해보셨을까요?

2023-05-17 02:27 UTC, jolly-n commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/request/SignUpRequest.java
>  ) {
Pattern에 대한 내용이 의도한대로 작동하지 않는거 같아요.

2023-05-17 07:16 UTC, hxnsxxm commented on src/main/java/net/blogteamthreecoderhivebe/domain/member/dto/response/SignUpResponse.java
> +                .isSignUp(member.getMemberRole() == USER)
👍

2023-05-18 06:05 UTC, jolly-n approved these changes
수고하셨습니다👍

2023-05-18 06:08 UTC, merged